name: enar_tutorial
dependencies:
- python=3.7
- beautifulsoup4
- bokeh
- cython
- graphviz
- ipython
- ipywidgets
- jupyter_client
- jupyter_core
- jupyterlab
- lxml
- matplotlib
- mkl-service
- notebook
- numpy
- pandas
- patsy
- pip
- pymc3
- pydot
- python-graphviz
- rpy2
- scikit-learn
- scipy
- seaborn
- setuptools
- simplegeneric
- sympy
- xlrd

